name: Scheduled Workflow

on:
    schedule:
        - cron: "53 9 * * *"
        
jobs:
    scheduled-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run a script
              run: echo "This workflow runs on the 20th of November at 09:45 AM if it's a Thursday."

